### PR TITLE
more consistent cli api naming proposal

### PR DESCRIPTION
**Pull request by depombo**
now top-level `app` cli commands and `credential`/`config` only differ in the nomenclature for editing them which is `upgrade` and `edit` respectively

### CODE REVIEW

**Review by dfellis — APPROVED** [review]

**Review by cdmistman — APPROVED** [review]

**Comment by aguillenv** [comment]
> now top-level `app` cli commands and `credential`/`config` only differ in the nomenclature for editing or removing them which is, `upgrade`/`terminate` and `edit`/`remove` respectively

Should we merge `terminate` and `remove` concepts eventually?

**Review by aguillenv — APPROVED** [review]

**Comment by depombo** [comment]
> > now top-level `app` cli commands and `credential`/`config` only differ in the nomenclature for editing or removing them which is, `upgrade`/`terminate` and `edit`/`remove` respectively
> 
> Should we merge `terminate` and `remove` concepts eventually?

I thought of it a bit, but the verbs feel more adequate to describe the respective nouns. Terminating a config/credential definitely does not make sense, so it would have to be `remove`. `edit`ing an app sounds pretty weird though.

**Comment by aguillenv** [comment]
> > > now top-level `app` cli commands and `credential`/`config` only differ in the nomenclature for editing or removing them which is, `upgrade`/`terminate` and `edit`/`remove` respectively
> > 
> > 
> > Should we merge `terminate` and `remove` concepts eventually?
> 
> I thought of it a bit, but the verbs feel more adequate to describe the respective nouns. Terminating a config/credential definitely does not make sense, so it would have to be `remove`. `edit`ing an app sounds pretty weird though.

No, for sure `edit` and `upgrade` mean different things. I'm referring to the concepts of `terminate` and `remove` (might be a different verb like `delete`). Might be easy in the future for the users to remember commands in my opinion. Remembering k8s, the `kubectl` command has almost the same verbs/actions (add, delete, edit) for different resources. But it's not a blocker, just something we can think about.

**Comment by depombo** [comment]
> > > > now top-level `app` cli commands and `credential`/`config` only differ in the nomenclature for editing or removing them which is, `upgrade`/`terminate` and `edit`/`remove` respectively
> > > 
> > > 
> > > Should we merge `terminate` and `remove` concepts eventually?
> > 
> > 
> > I thought of it a bit, but the verbs feel more adequate to describe the respective nouns. Terminating a config/credential definitely does not make sense, so it would have to be `remove`. `edit`ing an app sounds pretty weird though.
> 
> No, for sure `edit` and `upgrade` mean different things. I'm referring to the concepts of `terminate` and `remove` (might be a different verb like `delete`). Might be easy in the future for the users to remember commands in my opinion. Remembering k8s, the `kubectl` command has almost the same verbs/actions (add, delete, edit) for different resources. But it's not a blocker, just something we can think about.

Ah I like `delete`

**Comment by depombo** [comment]
> > > > > now top-level `app` cli commands and `credential`/`config` only differ in the nomenclature for editing or removing them which is, `upgrade`/`terminate` and `edit`/`remove` respectively
> > > > 
> > > > 
> > > > Should we merge `terminate` and `remove` concepts eventually?
> > > 
> > > 
> > > I thought of it a bit, but the verbs feel more adequate to describe the respective nouns. Terminating a config/credential definitely does not make sense, so it would have to be `remove`. `edit`ing an app sounds pretty weird though.
> > 
> > 
> > No, for sure `edit` and `upgrade` mean different things. I'm referring to the concepts of `terminate` and `remove` (might be a different verb like `delete`). Might be easy in the future for the users to remember commands in my opinion. Remembering k8s, the `kubectl` command has almost the same verbs/actions (add, delete, edit) for different resources. But it's not a blocker, just something we can think about.
> 
> Ah I like `delete`, let's go with that!

Talked offline with @dfellis and `delete`-ing a cluster still does not have the same implications as `terminate`-ing

**Pull request merged**
