### PR TITLE
Add Orderable interface, use to simplify min/max implementation.

### PR DESCRIPTION
**Pull request by dfellis**
I was not able to reproduce the issue pointed out by @MareinK. Will need to ask what the difference
is with this and what was tried before.

### CODE REVIEW

**Review by depombo — APPROVED** [review]

**Comment by dfellis** [comment]
Hmm... it does fail, but only when it's being used inside of a closure passed to an array method, not when it's used directly inside of a handler function.

**Comment by MareinK** [comment]
For me, these work on 0.1.19:

```alan
app.print(reduce([1, 2, 3], min))
app.print(reduce([1, 2, 3], add))
```

But these fail:

```alan
app.print([1, 2, 3].reduce(min))
app.print([1, 2, 3].reduce(add))
```

With these errors:

```
Cannot resolve operators with remaining statement
[1, 2, 3].reduce(min)
<Array<int64>> <int64>
```

```
Cannot resolve operators with remaining statement
[1, 2, 3].reduce(add)
<Array<int64>> <int64>
```

**Comment by dfellis** [comment]
Cannot resolve *operators*? What operator is it even referring to.

I will try to reproduce and see how it is getting confused like this, but probably not today. Housework on the weekends, usually.

**Comment by MareinK** [comment]
I found an extra hint: the below do work.

```alan
app.print(([1, 2, 3]).reduce(min))
app.print(([1, 2, 3]).reduce(add))
```

**Pull request merged**
